controllers/CartController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Response;
use yii\web\Controller;
use app\models\Category;
use app\models\Product;
use yz\shoppingcart\ShoppingCart;
use app\widgets\LeftCartWidget_oneItem;
use yii\web\NotFoundHttpException;
use app\models\forms\ChangeCartPositionForm;


class CartController extends Controller
{
    protected $category_roots;
    protected $cart;
    protected $errorMsg = [
        'notAjax' => 'Ошибка метода запроса',
        'notPostParam' => 'Нет необходимого параметра',
        'badId' => 'На данный момент такого продукта нет',
        'notValid' => 'Данные не прошли проверку',
    ];


    public function getCart() : ShoppingCart {
        if ( empty($this->cart) ) {
            $this->cart = new ShoppingCart();
        }
        return $this->cart;
    }

    public function beforeAction($action)
    {
        $top_button = $action->id;
        /* get all roots */
        $this->category_roots = Category::find()->roots()->all();
        /* set category_roots in main for draw topMenu */
        $this->view->params['category_roots'] = $this->category_roots;
        /* set quantity products */
        $this->view->params['cart_quantity'] = Product::getQuantityWord($this->getCart());
        $this->view->params['active_buttons'] = $this->setTopMenuButtons( $this->category_roots, $top_button );

        return parent::beforeAction($action);
    }



    public function actionShow()
    {
        $cart = $this->getCart();
        $modelForm = new ChangeCartPositionForm();

        $this->view->registerJsFile('js/Cart.js', ['depends' => 'app\assets\AppAsset']);
        $this->view->registerJsFile('js/jquery-validation/dist/jquery.validate.js', ['depends' => 'app\assets\AppAsset']);
        $this->view->registerJsFile('js/cart_show.js', ['depends' => 'app\assets\AppAsset']);
        return $this->render('show', ['cart'=>$cart, 'modelForm' => $modelForm]);
    }






    public function actionAdd()
    {
        $cart = $this->getCart();
        /* post param */
        $product_id = Yii::$app->request->post('product_id') ?: null;
        $quantity = (int)Yii::$app->request->post('quantity') ?: null;
        $get_html = Yii::$app->request->post('get_html');

        /* check AJAX */
        if (false == Yii::$app->request->isAjax) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
            /* check $post */
        } elseif ( false == Yii::$app->request->isPost || !$product_id || !$quantity ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
            /* check $product_id, get $product */
        } elseif ( !$product = Product::findOne(Yii::$app->request->post('product_id')) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }

        Yii::$app->response->format = Response::FORMAT_JSON;

        $cart->put($product, $quantity);
        $html_block = ( empty($get_html) ) ? null : LeftCartWidget_oneItem::widget(['product'=>$product]);

        $response = [
            'count'      => Product::getQuantityWord($this->cart),
            'html_block' => $html_block,
            'cost'       => sprintf( "%.2f", $cart->getCost()),
        ];

        return $response;
    }




    public function actionDeduct()
    {
        $cart = $this->getCart();
        /* post param */
        $product_id = Yii::$app->request->post('product_id') ?: null;
        /* check AJAX */
        if (false == Yii::$app->request->isAjax) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
            /* check $post */
        } elseif ( false == Yii::$app->request->isPost || !$product_id ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
            /* check $position */
        } elseif ( !$position = $cart->getPositionById(Yii::$app->request->post('product_id')) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }
        Yii::$app->response->format = Response::FORMAT_JSON;

        $position->quantity -= 1;
        if ($position->quantity < 1) { $cart->remove($position); }
        $cart->saveToSession();

        $response = [
            'prod_count' => $position->quantity,
            'totalCount' => Product::getQuantityWord($cart),
            'cost' => sprintf( "%.2f", $cart->getCost()),

        ];
        return $response;
    }



    public function actionUpdate()
    {
        $cart = $this->getCart();
        $modelForm = new ChangeCartPositionForm();
        /* check AJAX */
        if ( false == Yii::$app->request->isAjax ) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
        }
        elseif ( !$modelForm->load(Yii::$app->request->post()) ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
        }
        elseif ( !$modelForm->validate() ) {
            throw new NotFoundHttpException($this->errorMsg['notValid']);
        }
        elseif ( !$position = $cart->getPositionById($modelForm->product_id) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }
        Yii::$app->response->format = Response::FORMAT_JSON;

        $position->setQuantity($modelForm->quantity);
        $cart->saveToSession();

        $response = [
            'prod_cost' => sprintf( "%.2f", $position->cost),
            'cost' => sprintf( "%.2f", $cart->cost),
            'totalCount' => Product::getQuantityWord($cart),
        ];
        return $response;
    }



    public function actionDelete()
    {
        $cart = $this->getCart();
        $modelForm = new ChangeCartPositionForm();
        /* check AJAX */
        if ( false == Yii::$app->request->isAjax ) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
        }
        elseif ( !$modelForm->load(Yii::$app->request->post()) ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
        }
        elseif ( !$modelForm->validate() ) {
            throw new NotFoundHttpException($this->errorMsg['notValid']);
        }
        elseif ( !$position = $cart->getPositionById($modelForm->product_id) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }
        Yii::$app->response->format = Response::FORMAT_JSON;

        $cart->remove($position);
        //$cart->saveToSession();

        $response = [
            'cost' => sprintf( "%.2f", $cart->cost),
            'totalCount' => Product::getQuantityWord($cart),
        ];
        return $response;
    }



    /**
     * Fill top menu
     *
     * @param array $category_roots
     * @param string $top_button
     * @return array
     */
    protected function setTopMenuButtons(array $category_roots, $top_button = null)
    {
        $top_button =  $top_button ?: 'index';
        $activeButtons = [ 'index' => '', 'about' => '', 'contact' => ''];
        /* add Category button in menu */
        if ( !empty($category_roots) ) {
            foreach ($category_roots as $root) {
                $activeButtons[$root->name] = '';
            }
        }
        /* set class 'active' for button */
        if ( array_key_exists($top_button, $activeButtons) ) {
            $activeButtons[$top_button] = 'active';
        }
        return $activeButtons;
    }


}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\examples\ContactForm;
use app\widgets\ProductListWidget;
use yii\db\Expression;
use yii\web\Session;
use yz\shoppingcart\ShoppingCart;


class SiteController extends Controller
{

    protected $category_roots;
    protected $category_parents;
    protected $category_childs;

    protected $current_root;
    protected $current_parent;
    protected $current_child;

    protected $cart;
    protected $product;

    protected $node;


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function beforeAction($action)
    {
        /* primary button name */
        $top_button = $action->id;

        $this->cart = new ShoppingCart();

        /* $_GET contains - category_id / product_id */
        if ( $this->node = $this->categoryNodeByRequest() ) {
            /* current_root */
            $tmp_root = $this->node->parent;
            $this->current_root = ($tmp_root->isRoot()) ? $tmp_root : $tmp_root->parent;

            $top_button = $this->current_root->name;
        }

        /* get all roots */
        $this->category_roots = Category::find()->roots()->all();
        /* set category_roots in main for draw topMenu */
        $this->view->params['category_roots'] = $this->category_roots;
        $this->view->params['active_buttons'] = $this->setTopMenuButtons( $this->category_roots, $top_button );
        /* set quantity products */
        $this->view->params['cart_quantity'] = Product::getQuantityWord($this->cart);

        return parent::beforeAction($action);
    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $hit_products = Product::find()
            ->where(['hit'=> 1])
            ->orderBy(new Expression('rand()'))
            ->limit(4)
            ->all();

        //var_dump($hit_products); exit();

        $new_products = Product::find()
            ->where(['new'=> 1])
            ->orderBy(new Expression('rand()'))
            ->limit(4)
            ->all();

        $rand_products = Product::find()
            ->orderBy(new Expression('rand()'))
            ->limit(4)
            ->all();

        return $this->render('index', [
            'hit_products' => $hit_products,
            'new_products' => $new_products,
            'rand_products' => $rand_products
        ]);
    }



    /**
     * @param $category_id
     * @return string
     * @throws NotFoundHttpException
     *
     * Get:
     *  - приходит родительская категория
     *  - приходит дочерняя категория
     *
     * Ajax:
     *  - приходит родительская категория (все штаны)
     *  - приходит дочерняя категория (джинсы)
     */
    public function actionCategory($category_id)
    {
        if ( !$this->node || !$this->current_root ) {
            throw new NotFoundHttpException('На данный момент отсутсвует запрашиваемая категория.');
        }
        /* get parents category */
        $this->category_parents = $this->current_root->children;

        /* ancestors ids */
        $ancestors_ids = $this->node->getParentsIds();

        /* get products  */
        $ids = $this->node->getDescendantsIds(null, true) ?: [$this->node->id];
        $query = Product::find()->where(['in', 'category_id', $ids]);

        /* pagination */
        $countProducts = clone $query;
        $pages = new Pagination([
            'totalCount' => $countProducts->count(),
            'pageSize'   => 9,
            'route'      => 'category'
        ]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        /* If ajax */
        if ( Yii::$app->request->isAjax ) {
            return ProductListWidget::widget(['pages' => $pages, 'products' => $products]);
        }
        else {
            $params = [
                'pages'              => $pages,                  // for pagination (ProductListWidget)
                'products'           => $products,               // for content (ProductListWidget)
                'node'               => $this->node,             // for left menu
                'ancestors_ids'      => $ancestors_ids,          // for left menu
                'category_parents'   => $this->category_parents, // for left menu
            ];
            return $this->render('category', $params);
        }
    }


    /**
     * @param $product_id
     * @return string
     */
    public function actionProductDetail($product_id)
    {
        $product = Product::findOne($product_id);
        /* test */
        $this->cart = new ShoppingCart();
        $params = [
            'product' => $product,
            'child_category' => $this->node,
            'parent_category' => $this->node->parent,
            'cart' => $this->cart,
        ];
        $this->view->registerJsFile('js/Cart.js', ['depends' => 'app\assets\AppAsset']);
        $this->view->registerJsFile('js/product_detail.js', ['depends' => 'app\assets\AppAsset']);
        return $this->render('product_detail', $params);
    }



    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $this->view->params['activeBtn'] = 'about';
        return $this->render('about');
    }


    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        $this->view->params['activeBtn'] = 'contact';

        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }




    /**
     * @return mixed|null|static
     */
    protected function categoryNodeByRequest()
    {
        $node = null;
        if ( $category_id = Yii::$app->request->get('category_id') ) {
            $node = Category::findOne(['id'=>$category_id]);
        }
        elseif ( $product_id = Yii::$app->request->get('product_id') ) {
            $this->product = Product::findOne(['id'=>$product_id]);
            $node = $this->product->category;
        }
        return $node;
    }


    /**
     * Fill top menu
     *
     * @param array $category_roots
     * @param string $top_button
     * @return array
     */
    protected function setTopMenuButtons(array $category_roots, $top_button = null)
    {
        $top_button =  $top_button ?: 'index';
        $activeButtons = [ 'index' => '', 'about' => '', 'contact' => ''];
        /* add Category button in menu */
        if ( !empty($category_roots) ) {
            foreach ($category_roots as $root) {
                $activeButtons[$root->name] = '';
            }
        }
        /* set class 'active' for button */
        if ( array_key_exists($top_button, $activeButtons) ) {
            $activeButtons[$top_button] = 'active';
        }
        return $activeButtons;
    }






    /**************  TEST  *****************/
    /**************************************/


    public function actionTest1()
    {
        $test = [
            'key' => 'value',
        ];
        return $this->render('test', compact('test'));

    }



}

views/layouts/main.php
<?php

/* @var $this \yii\web\View
 * @var $content string
 */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\models\Category;
use yii\helpers\Url;

use app\assets\AppAsset;
use app\assets\ltAsset;
use yii\jui\JuiAsset;

/* Register Asset
------------------*/
AppAsset::register($this);
JuiAsset::register($this);
ltAsset::register($this);


/* Params
----------*/

//var_dump($this->params['active_buttons']); exit();
$activeButtons = $this->params['active_buttons'];
$category_roots = $this->params['category_roots'];
$cart_quantity = $this->params['cart_quantity'];


$user = Yii::$app->user->identity;
if (null != $user) {
    $greeting = 'Здравствуйте, '.$user->username ." <a href='".Url::to('/user/logout')."'><button class='btn btn-default btn-xs'> Выйти</button></a>";
} else {
    $greeting = "Здравствуйте, гость  <a href='".Url::to('/user/login')."'><button class='btn btn-default btn-xs'> Войти</button></a>";
}



?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head();
    // для примера:
    //$this->registerJsFile('js/html5shiv.js', ['position' => View::POS_HEAD, 'condition' => 'lte IE9']);
    ?>
</head>
<body>
<?php $this->beginBody() ?>

<!-- begin:navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#clotheshop-navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="clotheshop-navbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a class="disabled">CURRENCY</a></li>
                <li class="active"><a href="#">USD</a></li>
                <li><a href="#">EUR</a></li>
                <li><a href="#">IDR</a></li>
                <li class="divider-vertical"></li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">LANGUAGE <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">EN</a></li>
                        <li><a href="#">ID</a></li>
                        <li><a href="#">FR</a></li>
                        <li class="divider"></li>
                        <li><a href="#">IT</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>
<!-- end:navbar -->

<!-- begin:content -->
<div class="container">
    <!-- begin:logo -->
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6">
            <div class="logo">
                <h1><a href="index.html">Clothe<span>shop</span> </a></h1>
                <p>Clean and simple shopping cart</p>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6">
            <div class="account">
                <ul>
                    <li id="your-account">
                        <div class="hidden-xs">
                            <!--<h4><a href="#">Your Account</a></h4>-->
                            <h4>УЧЕТНАЯ ЗАПИСЬ</h4>
                            <p><?= $greeting ?></p>
                        </div>
                        <div class="visible-xs">
                            <a href="login.html" class="btn btn-primary"><i class="fa fa-user"></i></a>
                        </div>
                    </li>
                    <li>
                        <div class="hidden-xs">
                            <h4>Корзина</a></h4>
                            <a href="<?= Url::to('/cart/show'); ?>">
                                <p class="cart_total_count"><?= $cart_quantity; ?></p>
                            </a>
                        </div>
                        <div class="visible-xs">
                            <a href="<?= Url::to('/cart/show'); ?>" class="btn btn-primary"><span class="cart-item cart_total_count"><?= (int)$cart_quantity; ?></span> <i class="fa fa-shopping-cart"></i></a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- end:logo -->

    <!-- begin:nav-menus -->
    <div class="row">
        <div class="col-md-12">
            <div class="nav-menus">
                <ul class="nav nav-pills">

                    <!-- Главная -->
                    <li class="<?= $activeButtons['index'] ?>"><?= Html::a('Главная', ['site/index']) ?></li>


                    <!-- Categories Menu Items -->
                    <? foreach ($category_roots as $root) { ?>

                        <? if (!$root instanceof Category) continue; ?>
                        <li class="dropdown <?= $activeButtons[$root->name] ?>">
                            <?= Html::a( "$root->description <b class='caret'></b>", ['site/category'], ['data-toggle' => 'dropdown', 'class' => 'dropdown-toggle']) ?>
                            <ul class="dropdown-menu" id="menu1">

                                <? $parents = $root->children; ?>
                                <? foreach ($parents as $node) { ?>
                                    <li>
                                        <?= Html::a( $node['description'], ['site/category', 'category_id' => $node['id']] ); ?>
                                    </li>
                                <? } ?>

                            </ul>
                        </li>

                    <? } ?>


                    <!-- About -->
                    <li class="<?= $activeButtons['about'] ?>">
                        <?= Html::a('О нас', ['site/about']) ?>
                    </li>

                    <!-- Contact -->
                    <li class="<?= $activeButtons['contact'] ?>">
                        <?= Html::a('Контакты', ['site/contact']) ?>
                    </li>
                    <!-- TEST -->
                    <!--<li>
                        <?/*= Html::a('TEST', ['test/index']) */?>
                    </li>-->
                </ul>
            </div>
        </div>
    </div>
    <!-- end:nav-menus -->

    <? if ( !empty($message = Yii::$app->session->getFlash('success')) ) { ?>
            <div class="alert alert-success"> <?= $message ?> </div>
    <? } //endif ?>

    <? if ( !empty($exceptMsg = Yii::$app->session->getFlash('exceptionMsg')) ) { ?>
        <div class="alert alert-danger"> <?= $exceptMsg ?> </div>
    <? } //endif ?>


    <? echo $content ?>



    <!-- begin:footer -->
    <div class="row">
        <div class="col-sm-12 footer">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="widget">
                        <h3><span>Contact Info</span></h3>
                        <address>
                            No. 22, Bantul, Yogyakarta, Indonesia<br>
                            Call Us : (0274) 4411005<br>
                            Email : avriqq@gmail.com<br>
                        </address>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="widget">
                        <h3><span>Customer Support</span></h3>
                        <ul class="list-unstyled list-star">
                            <li><a href="#">FAQ</a></li>
                            <li><a href="#">Payment Option</a></li>
                            <li><a href="#">Booking Tips</a></li>
                            <li><a href="#">Information</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="widget">
                        <h3><span>Discover our store</span></h3>
                        <ul class="list-unstyled list-star">
                            <li><a href="#">California</a></li>
                            <li><a href="#">Bali</a></li>
                            <li><a href="#">Singapore</a></li>
                            <li><a href="#">Canada</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="widget">
                        <h3><span>Get Our Newsletter</span></h3>
                        <p>Subscribe to our newsletter and get exclusive deals straight to your inbox!</p>
                        <form>
                            <input type="email" class="form-control" name="email" placeholder="Your Email : "><br>
                            <input type="submit" class="btn btn-warning" value="Subscribe">
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- end:footer -->

    <!-- begin:copyright -->
    <div class="row">
        <div class="col-md-12 copyright">
            <div class="row">
                <div class="col-md-6 col-sm-6 copyright-left">
                    <p>Copyright &copy; Clotheshop 2012-<?= date('Y')?>. All right reserved.</p>
                </div>
                <div class="col-md-6 col-sm-6 copyright-right">
                    <ul class="list-unstyled list-social">
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- end:copyright -->

</div>
<!-- end:content -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main_v1.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/test.php
<?php

echo $content;