models/Order.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yz\shoppingcart\ShoppingCart;
use app\components\exceptions\CustomException;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property int $customer_id
 * @property string $created_at
 * @property string $updated_at
 * @property int $qty
 * @property int $sum
 * @property int $status 0 or 1
 *
 * @property OrderItems[] $orderItems
 * @property Customers $customer
 */
class Order extends ActiveRecord
{

    public static function tableName() {
        return 'orders';
    }

    /**
     * @inheritdoc
     */
    /*public function rules()
    {
        return [
            [['customer_id', 'qty', 'sum', 'status'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['qty', 'sum', 'status'], 'required'],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Customers::className(), 'targetAttribute' => ['customer_id' => 'id']],
        ];
    }*/

    /**
     * @inheritdoc
     */
    /*public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_id' => 'Customer ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'qty' => 'Qty',
            'sum' => 'Sum',
            'status' => 'Status',
        ];
    }*/

    public static function setOrder(Customer $customer, ShoppingCart $cart) : Order
    {
        if ( $cart->isEmpty ) {
            $except = new CustomException('Пользователь '. $customer->email .' пытается оформить пустой заказ.');
            throw $except->warningExcept('Ваша корзина пуста');
        }
        $order = new self();
        $order->customer_id = $customer->id;
        $order->qty = $cart->count;
        $order->sum = $cart->cost;
        if ( !$order->save() ) {
            $except = new CustomException('Ошибка при оформлении заказа || setOrder()');
            throw $except->errorExcept('Не удаётся оформить заказ');
        }
        return $order;
    }



    public static function setOrderItems(Order $order, ShoppingCart $cart)
    {
        $query = Yii::$app->db->createCommand( 'INSERT INTO order_items(order_id, product_id, price, qty, cost) 
                                                      VALUES(:order_id, :product_id, :price, :qty, :cost)' );
        try {
            foreach ($cart->getPositions() as $position ) {
                $query->bindValues([
                    ':order_id'=>$order->id,
                    ':product_id'=>$position->id,
                    ':price'=>$position->price,
                    ':qty'=>$position->quantity,
                    ':cost'=>$position->cost,
                ])->execute();
            }
        } catch (\Throwable $e) {
            /* if throw yii exception - throw CustomException */
            $except = new CustomException( $e->getMessage() . '|| setOrderItems()');
            throw $except->errorExcept('Не удаётся оформить заказ');
        }
    }



    public function getOrderItems() {
        //return $this->hasMany(OrderItems::className(), ['order_id' => 'id']);
        return Yii::$app->db->createCommand('SELECT * FROM `order_items` WHERE order_id=:id')
            ->bindValue(':id', $this->id)
            ->queryAll();
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(Customer::class, ['id' => 'customer_id']);
    }
}

controllers/OrderController.php
<?php
/**
 * Created by PhpStorm.
 * User: Toha
 * Date: 07.04.2018
 * Time: 18:49
 */

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use Yii;
use yii\web\Controller;
use app\models\Customer;
use app\models\Order;
use yz\shoppingcart\ShoppingCart;
use app\models\forms\CustomerForm;
use app\components\DataLayoutTrait;
use app\components\exceptions\CustomException;

class OrderController extends Controller
{
    use DataLayoutTrait;


    public function beforeAction($action)
    {
        $top_button = $action->id;
        /* get all roots */
        $this->category_roots = Category::find()->roots()->all();
        /* set category_roots in main for draw topMenu */
        $this->view->params['category_roots'] = $this->category_roots;
        /* set quantity products */
        $this->view->params['cart_quantity'] = Product::getQuantityWord($this->getCart());
        $this->view->params['active_buttons'] = $this->setTopMenuButtons( $this->category_roots, $top_button );

        return parent::beforeAction($action);
    }

    /**
     * Show customer form
     *
     * @return string
     */
    public function actionCustomerForm()
    {
        $formModel = new CustomerForm();
        $user = Yii::$app->user->identity;

        $cart = new ShoppingCart();
        try {
            if ($cart->isEmpty) {
                $except = new CustomException( 'Пустая корзина || actionCustomerForm()');
                throw $except->infoExcept('Чтобы оформить заказ необходимо выбрать товар.');
            }
        } catch (CustomException $e) {
            $e->init();
        }

        return $this->render('customer_form', compact('formModel', 'user'));
    }


    /**
     * Create order
     *
     * @return string
     * @throws \yii\db\Exception
     */
    public function actionCreateOrder()
    {
        $cart = new ShoppingCart();
        $user = Yii::$app->user->identity;
        $formModel = new CustomerForm();

        $transaction = Yii::$app->db->beginTransaction();

        //dd($customer_id);
        /* тут оказия если пользователя нет */
        if (!$user) {
            return Yii::$app->runAction('site/index');
        }
        /* и тут оказия если customer нет */
        if ( !isset($user->customer->id)) {
            return Yii::$app->runAction('site/index');
        }


        try {
            if ( $formModel->load(Yii::$app->request->post()) && $customer = $formModel->fillModel( $user->customer->id)) {
                /* set order */


                dd($customer);
                $order = Order::setOrder($customer, $cart);
                /* set order-items */
                Order::setOrderItems($order, $cart);
                /* set last_order_id */
                $customer->setLastOrderId($order->id);
                if (!empty($user)) {
                    $user->saveCustomerId($customer->id);
                }
                $this->sendOrderEmail($customer, $order);
                Yii::$app->session->setFlash('success', 'Спасибо за заказ.', false);
                $cart->removeAll();
                $this->redirect(Yii::$app->getHomeUrl());
            }

            $transaction->commit();

        } catch (CustomException $e) {
            $transaction->rollBack();
            $e->init();
        }
        return $this->render('customer_form', compact('formModel', 'user'));
    }


    /**
     * @param Customer $customer
     * @param Order $order
     * @throws CustomException
     */
    public function sendOrderEmail(Customer $customer, Order $order) {
        try {
            Yii::$app->mailer->compose()
                ->setFrom('al-loco@mail.ru')
                ->setTo((string)$customer->email)
                ->setSubject('Заказ №' . $order->id)
                ->setTextBody($customer->first_name . ', ваш заказ № '. $order->id . ', спасибо за доверие.')
                ->send();
        } catch (\Throwable $e) {
            $except = new CustomException( $e->getMessage() . '|| sendOrderEmails()');
            throw $except->errorExcept('Не удаётся оформить заказ, такого email нет.');
        }
    }




    /**
     * Fill top menu
     *
     * @param array $category_roots
     * @param string $top_button
     * @return array
     */
    protected function setTopMenuButtons(array $category_roots, $top_button = null)
    {
        $top_button =  $top_button ?: 'index';
        $activeButtons = [ 'index' => '', 'about' => '', 'contact' => ''];
        /* add Category button in menu */
        if ( !empty($category_roots) ) {
            foreach ($category_roots as $root) {
                $activeButtons[$root->name] = '';
            }
        }
        /* set class 'active' for button */
        if ( array_key_exists($top_button, $activeButtons) ) {
            $activeButtons[$top_button] = 'active';
        }
        return $activeButtons;
    }



    /******** TEST **********/
    /***********************/

    public function actionTest()
    {

        $test = [
            'key' => 'value',
        ];
        return $this->render('test', compact('test'));

    }



}

controllers/UserController.php
<?php

namespace app\controllers;

use app\components\exceptions\CustomException;
use app\models\forms\SignupForm;
use app\models\forms\LoginForm;
use Yii;
use yii\web\Controller;
use app\models\Category;
use app\models\Product;
use yz\shoppingcart\ShoppingCart;



class UserController extends Controller
{
    protected $cart;
    protected $category_roots;


    public function getCart() : ShoppingCart {
        if ( empty($this->cart) ) {
            $this->cart = new ShoppingCart();
        }
        return $this->cart;
    }

    public function beforeAction($action)
    {
        $top_button = $action->id;
        /* get all roots */
        $this->category_roots = Category::find()->roots()->all();
        /* set category_roots in main for draw topMenu */
        $this->view->params['category_roots'] = $this->category_roots;
        /* set quantity products */
        $this->view->params['cart_quantity'] = Product::getQuantityWord($this->getCart());
        $this->view->params['active_buttons'] = $this->setTopMenuButtons( $this->category_roots, $top_button );

        return parent::beforeAction($action);
    }



    /**
     * @return string|\yii\web\Response
     */
    public function actionSignup()
    {
        $transaction = Yii::$app->db->beginTransaction();
        $signupForm = new SignupForm();
        $loginForm = new LoginForm();
        try {
            if ( Yii::$app->user->isGuest && $signupForm->load(Yii::$app->request->post()) && $user = $signupForm->save() ) {
                Yii::$app->session->setFlash('success', 'Регистрация прошла успешно.');
                $transaction->commit();
                Yii::$app->user->login( $user );

                return $this->redirect( /*(Yii::$app->request->referrer) ?:*/ Yii::$app->getHomeUrl());
            }
        } catch (CustomException $e) {
            $transaction->rollBack();
            $e->init();
        }
        return $this->render('signup', compact('signupForm', 'loginForm'));
    }




    public function actionLogin()
    {
        $signupForm = new SignupForm();
        $loginForm = new LoginForm();
        if ( Yii::$app->user->isGuest && $loginForm->load(Yii::$app->request->post()) && $loginForm->login() ) {
            Yii::$app->session->setFlash('success', 'Вы успешно авторизированы.');
            return $this->redirect( Yii::$app->session->getFlash('go_back') ?: Yii::$app->getHomeUrl());
        }
        Yii::$app->session->setFlash('go_back', Yii::$app->request->referrer);
        return $this->render('login', compact('signupForm', 'loginForm'));
    }


    public function actionLogout()
    {
        Yii::$app->user->logout(false);
        return $this->redirect( /*(Yii::$app->request->referrer) ?:*/ Yii::$app->getHomeUrl());
    }


    /**
     * Fill top menu
     *
     * @param array $category_roots
     * @param string $top_button
     * @return array
     */
    protected function setTopMenuButtons(array $category_roots, $top_button = null)
    {
        $top_button =  $top_button ?: 'index';
        $activeButtons = [ 'index' => '', 'about' => '', 'contact' => ''];
        /* add Category button in menu */
        if ( !empty($category_roots) ) {
            foreach ($category_roots as $root) {
                $activeButtons[$root->name] = '';
            }
        }
        /* set class 'active' for button */
        if ( array_key_exists($top_button, $activeButtons) ) {
            $activeButtons[$top_button] = 'active';
        }
        return $activeButtons;
    }






    /********************* TEST ************************/


    public function actionOne()
    {
        $this->redirect( (Yii::$app->request->referrer) ?: Yii::$app->getHomeUrl() );
    }

}

views/order/customer_form.php
<?php
/* @var $formModel app\models\forms\CustomerForm */
/* @var $user app\models\User */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;


$customer = ($user) ? $user->customer : null;

?>
<div class="row">
    <?php
    if($customer) { ?>
        <div class="col-md-6 col-sm-6">
            <h3>Данные о покупателе</h3>
            <hr />
            <?php $form = ActiveForm::begin(['class'=>'form-group', 'action' => ['order/create-order']]) ?>
            <div class="form-group">
                <?= $form->field($formModel, 'first_name')->textInput(['value' => $customer->first_name]) ?>
            </div>
            <div class="form-group">
                <?= $form->field($formModel, 'last_name')->textInput(['value' => $customer->last_name]) ?>
            </div>
            <div class="form-group">
                <?= $form->field($formModel, 'email')->textInput(['value' => (string)$customer->email ?: (string)$user->email]) ?>
            </div>
            <div class="form-group">
                <?= $form->field($formModel, 'address')->textInput(['value' => $customer->address]) ?>
            </div>
            <div class="form-group">
                <?= $form->field($formModel, 'phone')->textInput(['value' => $customer->phone]) ?>
            </div>
            <? if (!$user) { ?>
                <div class="alert alert-success" role="alert">
                    Вы сможете просматривать историю ваших заказов если <a href="<?= Url::to('/user/login') ?>" class="alert-link">войдете или зарегестрируетесь</a>.
                </div>
            <? } ?>
            <?= Html::a('Назад', 'javascript:history.back()', ['class' => 'btn btn-default']) ?>
            <?= Html::submitButton('Готово', ['class' => 'btn btn-green pull-right', 'name' => 'signup-button']) ?>
            <?php ActiveForm::end() ?>
        </div>
    <?php }
    else { ?>
        <div class="col-md-6 col-sm-6">
            <h3>Данные о покупателе</h3>
            <hr />
            <?php $form = ActiveForm::begin(['class'=>'form-group', 'action' => ['order/create-order']]) ?>
            <div class="form-group">
                <?= $form->field($formModel, 'first_name')->textInput(['placeholder' => 'First name']) ?>
            </div>
            <div class="form-group">
                <?= $form->field($formModel, 'last_name')->textInput(['placeholder' => 'Last name']) ?>
            </div>
            <div class="form-group">
                <?= $form->field($formModel, 'email')->textInput(['placeholder' => 'Email']) ?>
            </div>
            <div class="form-group">
                <?= $form->field($formModel, 'address')->textInput(['placeholder' => 'Address']) ?>
            </div>
            <div class="form-group">
                <?= $form->field($formModel, 'phone')->textInput(['placeholder' => 'Phone']) ?>
            </div>
            <? if (!$user) { ?>
                <div class="alert alert-success" role="alert">
                    Вы сможете просматривать историю ваших заказов если <a href="<?= Url::to('/user/login') ?>" class="alert-link">войдете или зарегестрируетесь</a>.
                </div>
            <? } ?>
            <?= Html::a('Назад', 'javascript:history.back()', ['class' => 'btn btn-default']) ?>
            <?= Html::submitButton('Готово', ['class' => 'btn btn-green pull-right', 'name' => 'signup-button']) ?>
            <?php ActiveForm::end() ?>
        </div>
    <?php } ?>
</div>

views/order/test.php
<?php

var_dump($test);