controllers/CartController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Response;
use yii\web\Controller;
use app\models\Category;
use app\models\Product;
use yz\shoppingcart\ShoppingCart;
use app\widgets\LeftCartWidget_oneItem;
use yii\web\NotFoundHttpException;
use app\models\forms\ChangeCartPositionForm;


class CartController extends Controller
{
    protected $category_roots;
    protected $cart;
    protected $errorMsg = [
        'notAjax' => 'Ошибка метода запроса',
        'notPostParam' => 'Нет необходимого параметра',
        'badId' => 'На данный момент такого продукта нет',
        'notValid' => 'Данные не прошли проверку',
    ];


    public function getCart() : ShoppingCart {
        if ( empty($this->cart) ) {
            $this->cart = new ShoppingCart();
        }
        return $this->cart;
    }

    public function beforeAction($action)
    {
        $top_button = $action->id;
        /* get all roots */
        $this->category_roots = Category::find()->roots()->all();
        /* set category_roots in main for draw topMenu */
        $this->view->params['category_roots'] = $this->category_roots;
        /* set quantity products */
        $this->view->params['cart_quantity'] = Product::getQuantityWord($this->getCart());
        $this->view->params['active_buttons'] = $this->setTopMenuButtons( $this->category_roots, $top_button );

        return parent::beforeAction($action);
    }



    public function actionShow()
    {
        $cart = $this->getCart();
        $modelForm = new ChangeCartPositionForm();

        $this->view->registerJsFile('js/Cart.js', ['depends' => 'app\assets\AppAsset']);
        $this->view->registerJsFile('js/jquery-validation/dist/jquery.validate.js', ['depends' => 'app\assets\AppAsset']);
        $this->view->registerJsFile('js/cart_show.js', ['depends' => 'app\assets\AppAsset']);
        return $this->render('show', ['cart'=>$cart, 'modelForm' => $modelForm]);
    }






    public function actionAdd()
    {
        $cart = $this->getCart();
        /* post param */
        $product_id = Yii::$app->request->post('product_id') ?: null;
        $quantity = (int)Yii::$app->request->post('quantity') ?: null;
        $get_html = Yii::$app->request->post('get_html');

        /* check AJAX */
        if (false == Yii::$app->request->isAjax) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
            /* check $post */
        } elseif ( false == Yii::$app->request->isPost || !$product_id || !$quantity ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
            /* check $product_id, get $product */
        } elseif ( !$product = Product::findOne(Yii::$app->request->post('product_id')) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }

        Yii::$app->response->format = Response::FORMAT_JSON;

        $cart->put($product, $quantity);
        $html_block = ( empty($get_html) ) ? null : LeftCartWidget_oneItem::widget(['product'=>$product]);

        $response = [
            'count'      => Product::getQuantityWord($this->cart),
            'html_block' => $html_block,
            'cost'       => sprintf( "%.2f", $cart->getCost()),
        ];

        return $response;
    }




    public function actionDeduct()
    {
        $cart = $this->getCart();
        /* post param */
        $product_id = Yii::$app->request->post('product_id') ?: null;
        /* check AJAX */
        if (false == Yii::$app->request->isAjax) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
            /* check $post */
        } elseif ( false == Yii::$app->request->isPost || !$product_id ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
            /* check $position */
        } elseif ( !$position = $cart->getPositionById(Yii::$app->request->post('product_id')) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }
        Yii::$app->response->format = Response::FORMAT_JSON;

        $position->quantity -= 1;
        if ($position->quantity < 1) { $cart->remove($position); }
        $cart->saveToSession();

        $response = [
            'prod_count' => $position->quantity,
            'totalCount' => Product::getQuantityWord($cart),
            'cost' => sprintf( "%.2f", $cart->getCost()),

        ];
        return $response;
    }



    public function actionUpdate()
    {
        $cart = $this->getCart();
        $modelForm = new ChangeCartPositionForm();
        /* check AJAX */
        if ( false == Yii::$app->request->isAjax ) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
        }
        elseif ( !$modelForm->load(Yii::$app->request->post()) ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
        }
        elseif ( !$modelForm->validate() ) {
            throw new NotFoundHttpException($this->errorMsg['notValid']);
        }
        elseif ( !$position = $cart->getPositionById($modelForm->product_id) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }
        Yii::$app->response->format = Response::FORMAT_JSON;

        $position->setQuantity($modelForm->quantity);
        $cart->saveToSession();

        $response = [
            'prod_cost' => sprintf( "%.2f", $position->cost),
            'cost' => sprintf( "%.2f", $cart->cost),
            'totalCount' => Product::getQuantityWord($cart),
        ];
        return $response;
    }



    public function actionDelete()
    {
        $cart = $this->getCart();
        $modelForm = new ChangeCartPositionForm();
        /* check AJAX */
        if ( false == Yii::$app->request->isAjax ) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
        }
        elseif ( !$modelForm->load(Yii::$app->request->post()) ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
        }
        elseif ( !$modelForm->validate() ) {
            throw new NotFoundHttpException($this->errorMsg['notValid']);
        }
        elseif ( !$position = $cart->getPositionById($modelForm->product_id) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }
        Yii::$app->response->format = Response::FORMAT_JSON;

        $cart->remove($position);
        //$cart->saveToSession();

        $response = [
            'cost' => sprintf( "%.2f", $cart->cost),
            'totalCount' => Product::getQuantityWord($cart),
        ];
        return $response;
    }



    /**
     * Fill top menu
     *
     * @param array $category_roots
     * @param string $top_button
     * @return array
     */
    protected function setTopMenuButtons(array $category_roots, $top_button = null)
    {
        $top_button =  $top_button ?: 'index';
        $activeButtons = [ 'index' => '', 'about' => '', 'contact' => ''];
        /* add Category button in menu */
        if ( !empty($category_roots) ) {
            foreach ($category_roots as $root) {
                $activeButtons[$root->name] = '';
            }
        }
        /* set class 'active' for button */
        if ( array_key_exists($top_button, $activeButtons) ) {
            $activeButtons[$top_button] = 'active';
        }
        return $activeButtons;
    }


}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\examples\ContactForm;
use app\widgets\ProductListWidget;
use yii\db\Expression;
use yii\web\Session;
use yz\shoppingcart\ShoppingCart;


class SiteController extends Controller
{

    protected $category_roots;
    protected $category_parents;
    protected $category_childs;

    protected $current_root;
    protected $current_parent;
    protected $current_child;

    protected $cart;
    protected $product;

    protected $node;


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function beforeAction($action)
    {
        /* primary button name */
        $top_button = $action->id;

        $this->cart = new ShoppingCart();

        /* $_GET contains - category_id / product_id */
        if ( $this->node = $this->categoryNodeByRequest() ) {
            /* current_root */
            $tmp_root = $this->node->parent;
            $this->current_root = ($tmp_root->isRoot()) ? $tmp_root : $tmp_root->parent;

            $top_button = $this->current_root->name;
        }

        /* get all roots */
        $this->category_roots = Category::find()->roots()->all();
        /* set category_roots in main for draw topMenu */
        $this->view->params['category_roots'] = $this->category_roots;
        $this->view->params['active_buttons'] = $this->setTopMenuButtons( $this->category_roots, $top_button );
        /* set quantity products */
        $this->view->params['cart_quantity'] = Product::getQuantityWord($this->cart);

        return parent::beforeAction($action);
    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $hit_products = Product::find()
            ->where(['hit'=> 1])
            ->orderBy(new Expression('rand()'))
            ->limit(4)
            ->all();

        //var_dump($hit_products); exit();

        $new_products = Product::find()
            ->where(['new'=> 1])
            ->orderBy(new Expression('rand()'))
            ->limit(4)
            ->all();

        $rand_products = Product::find()
            ->orderBy(new Expression('rand()'))
            ->limit(4)
            ->all();

        return $this->render('index', [
            'hit_products' => $hit_products,
            'new_products' => $new_products,
            'rand_products' => $rand_products
        ]);
    }



    /**
     * @param $category_id
     * @return string
     * @throws NotFoundHttpException
     *
     * Get:
     *  - приходит родительская категория
     *  - приходит дочерняя категория
     *
     * Ajax:
     *  - приходит родительская категория (все штаны)
     *  - приходит дочерняя категория (джинсы)
     */
    public function actionCategory($category_id)
    {
        if ( !$this->node || !$this->current_root ) {
            throw new NotFoundHttpException('На данный момент отсутсвует запрашиваемая категория.');
        }
        /* get parents category */
        $this->category_parents = $this->current_root->children;

        /* ancestors ids */
        $ancestors_ids = $this->node->getParentsIds();

        /* get products  */
        $ids = $this->node->getDescendantsIds(null, true) ?: [$this->node->id];
        $query = Product::find()->where(['in', 'category_id', $ids]);

        /* pagination */
        $countProducts = clone $query;
        $pages = new Pagination([
            'totalCount' => $countProducts->count(),
            'pageSize'   => 9,
            'route'      => 'category'
        ]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        /* If ajax */
        if ( Yii::$app->request->isAjax ) {
            return ProductListWidget::widget(['pages' => $pages, 'products' => $products]);
        }
        else {
            $params = [
                'pages'              => $pages,                  // for pagination (ProductListWidget)
                'products'           => $products,               // for content (ProductListWidget)
                'node'               => $this->node,             // for left menu
                'ancestors_ids'      => $ancestors_ids,          // for left menu
                'category_parents'   => $this->category_parents, // for left menu
            ];
            return $this->render('category', $params);
        }
    }


    /**
     * @param $product_id
     * @return string
     */
    public function actionProductDetail($product_id)
    {
        $product = Product::findOne($product_id);
        /* test */
        $this->cart = new ShoppingCart();
        $params = [
            'product' => $product,
            'child_category' => $this->node,
            'parent_category' => $this->node->parent,
            'cart' => $this->cart,
        ];
        $this->view->registerJsFile('js/Cart.js', ['depends' => 'app\assets\AppAsset']);
        $this->view->registerJsFile('js/product_detail.js', ['depends' => 'app\assets\AppAsset']);
        return $this->render('product_detail', $params);
    }



    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $this->view->params['activeBtn'] = 'about';
        return $this->render('about');
    }


    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        $this->view->params['activeBtn'] = 'contact';

        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }




    /**
     * @return mixed|null|static
     */
    protected function categoryNodeByRequest()
    {
        $node = null;
        if ( $category_id = Yii::$app->request->get('category_id') ) {
            $node = Category::findOne(['id'=>$category_id]);
        }
        elseif ( $product_id = Yii::$app->request->get('product_id') ) {
            $this->product = Product::findOne(['id'=>$product_id]);
            $node = $this->product->category;
        }
        return $node;
    }


    /**
     * Fill top menu
     *
     * @param array $category_roots
     * @param string $top_button
     * @return array
     */
    protected function setTopMenuButtons(array $category_roots, $top_button = null)
    {
        $top_button =  $top_button ?: 'index';
        $activeButtons = [ 'index' => '', 'about' => '', 'contact' => ''];
        /* add Category button in menu */
        if ( !empty($category_roots) ) {
            foreach ($category_roots as $root) {
                $activeButtons[$root->name] = '';
            }
        }
        /* set class 'active' for button */
        if ( array_key_exists($top_button, $activeButtons) ) {
            $activeButtons[$top_button] = 'active';
        }
        return $activeButtons;
    }






    /**************  TEST  *****************/
    /**************************************/


    public function actionTest1()
    {
        $test = [
            'key' => 'value',
        ];
        return $this->render('test', compact('test'));

    }



}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'О нас';
$this->params['breadcrumbs'][] = $this->title;
?>

<h1><?= Html::encode($this->title) ?></h1>

<!-- begin:article -->
<div class="row">
    <div class="col-md-3 col-sm-4 sidebar">
        <div class="row">
            <div class="col-md-12">
                <div class="widget">
                    <h3>Lorem ipsum</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Fusce varius quam elementum metus vulputate lacinia. Class aptent taciti sociosqu ad.</p>
                </div>

                <div class="widget">
                    <h3>Lorem ipsum dolor</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a lorem eget dui lacinia ullamcorper. Nunc a mi ipsum, at porta odio. Vivamus hendrerit, massa et molestie bibendum, lacus neque.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-9 col-sm-8 content">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb">
                    <li><a href="#">Home</a></li>
                    <li class="active">About</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h2>About Us <small>Subtext for header</small></h2>
                </div>

                <blockquote>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venenatis.</p>
                    <small>Someone famous in <cite title="">Body of work</cite></small>
                </blockquote>

                <h3>Who we are ?</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras quis mi quis purus consectetur adipiscing vel eget nibh.
                    Vivamus sed tortor massa, ac consequat sem. Suspendisse potenti. Donec blandit nibh luctus nibh dignissim vulputate.
                    Sed interdum, augue at pulvinar dapibus, libero nibh semper massa, ut feugiat leo tortor vitae ante.
                    Aliquam erat volutpat. Suspendisse luctus felis sit amet ipsum ornare eget commodo urna pharetra.
                    Duis hendrerit risus ac nulla mattis rhoncus. Praesent iaculis egestas purus et varius.</p>

                <h3>Our team</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras quis mi quis purus consectetur adipiscing vel eget nibh.
                    Vivamus sed tortor massa, ac consequat sem. Suspendisse potenti. Donec blandit nibh luctus nibh dignissim vulputate.
                    Sed interdum, augue at pulvinar dapibus, libero nibh semper massa, ut feugiat leo tortor vitae ante.
                    Aliquam erat volutpat. Suspendisse luctus felis sit amet ipsum ornare eget commodo urna pharetra.
                    Duis hendrerit risus ac nulla mattis rhoncus. Praesent iaculis egestas purus et varius.</p>

            </div>
        </div>
    </div>
</div>
<!-- end:article -->

views/site/category.php
<?php

/* @var $this yii\web\View */

use yii\widgets\Breadcrumbs;
use yii\helpers\Html;
use app\widgets\CategoryListWidget;
use app\widgets\ProductListWidget;

//$this->title = $parent->description;

/* TEST */
//var_dump($products);
?>


<div class="row">
    <hr>


    <!-- begin:sidebar -->
    <div class="col-md-3 col-sm-4 sidebar">
        <!-- Left menu -->
        <div id="left_menu">

            <?= CategoryListWidget::widget( compact('category_parents', 'node', 'ancestors_ids') ); ?>

        </div>
    </div>


    <!-- begin:content -->
    <div class="col-md-9 col-sm-8 content">
        <!-- Ajax Container -->
        <div id="ajax_container">

            <?= ProductListWidget::widget(['pages' => $pages, 'products' => $products]) ?>

        </div>
    </div>
    <!-- end:content -->

</div>


views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/product_detail.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use app\widgets\LeftCartWidget;

//var_dump($product);
//var_dump($category);

//var_dump($cart);

?>
<!-- begin:article -->
<div class="row">
    <!-- begin:sidebar -->
    <div class="col-md-3 col-sm-4 sidebar">
        <div class="row">
            <div class="col-md-12">

                <!-- break -->
                <div class="widget">
                    <div class="widget-title">
                        <h3>Payment Confirmation</h3>
                    </div>
                    <p>Already make a payment ? please confirm your payment by filling <a href="confirm.html">this form</a></p>
                </div>

                <!-- left cart -->
                <?= LeftCartWidget::widget(['cart'=>$cart]); ?>

            </div>
        </div>
    </div>
    <!-- end:sidebar -->

    <!-- begin:content -->
    <div class="col-md-9 col-sm-8 content">

        <!-- Breadcrumbs -->
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb">
                    <!-- Back -->
                    <li id="back_breadcrumb"><a href="javascript:history.back()"><span class="glyphicon glyphicon-chevron-left"></span>назад</a></li>
                    <li><?= Html::a($parent_category->description, 'category?category_id='. $parent_category->id); ?></li>
                    <li><?= Html::a($child_category->description, 'category?category_id='. $child_category->id); ?></li>
                    <li class="active"><?= $product->description; ?></li>
                    </ol>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="heading-title">
                    <h2><span><?= $product->description; ?></span> <span class="text-yellow"></span></h2>
                </div>
                <div class="row">

                    <!-- begin:product-IMAGE-slider -->
                    <div class="col-md-6 col-sm-6">
                        <div id="product-single" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="item active">
                                    <div class="product-single">
                                        <img src="<?= Url::to('@prodImg/'.$product->img) ?>" class="img-responsive">
                                    </div>
                                </div>
<!--                                <div class="item">-->
<!--                                    <div class="product-single">-->
<!--                                        <img src="img/product11.jpg" class="img-responsive">-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                                <div class="item">-->
<!--                                    <div class="product-single">-->
<!--                                        <img src="img/product12.jpg" class="img-responsive">-->
<!--                                    </div>-->
<!--                                </div>-->
                            </div>

                            <a class="left carousel-control" href="#product-single" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right carousel-control" href="#product-single" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div>
                    <!-- end:product-IMAGE-slider -->


                    <!-- begin:product-spesification -->
                    <div class="col-md-6 col-sm-6">
                        <div class="single-desc">
                            <form>
                      <span class="visible-xs">
                          <strong>Blackbox / AF0012 / In Stock</strong>
                      </span>

                                <table>
                                    <tbody>
                                    <tr class="hidden-xs">
                                        <td><strong>Brand</strong></td>
                                        <td>:</td>
                                        <td>Blackbox</td>
                                    </tr>
                                    <tr class="hidden-xs">
                                        <td><strong>Product Code</strong></td>
                                        <td>:</td>
                                        <td>AF0012</td>
                                    </tr>
                                    <tr class="hidden-xs">
                                        <td><strong>Availability</strong></td>
                                        <td>:</td>
                                        <td>In Stock</td>
                                    </tr>
                                    <tr>
                                        <!-- Price -->
                                        <td colspan="3">
<!--                                            <span class="price-old">--><?//= sprintf( "%.2f",($product->price * 1.20) ) ?><!-- руб</span>-->
                                            <span class="price"><?= $product->price ?> руб</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><strong>Color</strong></td>
                                        <td>:</td>
                                        <td>
                                            <select class="form-control">
                                                <option>Black</option>
                                                <option>Green</option>
                                                <option>Blue</option>
                                                <option>Yellow</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><strong>Size</strong></td>
                                        <td>:</td>
                                        <td>
                                            <select class="form-control">
                                                <option>XS</option>
                                                <option>S</option>
                                                <option>M</option>
                                                <option>L</option>
                                                <option>XL</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr id="add_quantity">
                                        <td><strong>Количество</strong></td>
                                        <td>:</td>
                                        <td>
                                            <input type="text" class="form-control" value="1">
                                        </td>
                                    </tr>
                                    <tr id="add_button">
                                        <!-- Add to cart -->
                                        <td colspan="3">
                                            <a href="<?= Url::to(['cart/add', 'product_id' => $product->id])?>"
                                               data-product_id="<?= $product->id; ?>" class="btn btn-sm btn-success">Добавить</a>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </form>
                        </div>
                    </div>
                    <!-- end:product-spesification -->
                </div>
                <!-- break -->
                <!-- begin:product-detail -->
                <div class="row">
                    <div class="col-md-12 content-detail">
                        <ul id="myTab" class="nav nav-tabs">
                            <li class="active"><a href="#desc" data-toggle="tab">Description</a></li>
                            <li class=""><a href="#care" data-toggle="tab">Care</a></li>
                            <li class=""><a href="#size" data-toggle="tab">Sizing</a></li>
                        </ul>


                    </div>
                </div>
                <!-- end:product-detail -->


            </div>
        </div>
    </div>
    <!-- end:content -->
</div>
<!-- end:article -->

views/site/test.php
<?php

//var_dump($cart);
var_dump($positions);
var_dump($cart);
var_dump($cart->cost);
var_dump($_SESSION);
var_dump($cart->cartId);

?>
<a href="#" class="btn btn-sm btn-primary">Добавить</a>

views/site/user_error.php
<?= $message ?>