controllers/CartController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Response;
use yii\web\Controller;
use app\models\Category;
use app\models\Product;
use yz\shoppingcart\ShoppingCart;
use app\widgets\LeftCartWidget_oneItem;
use yii\web\NotFoundHttpException;
use app\models\forms\ChangeCartPositionForm;


class CartController extends Controller
{
    protected $category_roots;
    protected $cart;
    protected $errorMsg = [
        'notAjax' => 'Ошибка метода запроса',
        'notPostParam' => 'Нет необходимого параметра',
        'badId' => 'На данный момент такого продукта нет',
        'notValid' => 'Данные не прошли проверку',
    ];


    public function getCart() : ShoppingCart {
        if ( empty($this->cart) ) {
            $this->cart = new ShoppingCart();
        }
        return $this->cart;
    }

    public function beforeAction($action)
    {
        $top_button = $action->id;
        /* get all roots */
        $this->category_roots = Category::find()->roots()->all();
        /* set category_roots in main for draw topMenu */
        $this->view->params['category_roots'] = $this->category_roots;
        /* set quantity products */
        $this->view->params['cart_quantity'] = Product::getQuantityWord($this->getCart());
        $this->view->params['active_buttons'] = $this->setTopMenuButtons( $this->category_roots, $top_button );

        return parent::beforeAction($action);
    }



    public function actionShow()
    {
        $cart = $this->getCart();
        $modelForm = new ChangeCartPositionForm();

        $this->view->registerJsFile('js/Cart.js', ['depends' => 'app\assets\AppAsset']);
        $this->view->registerJsFile('js/jquery-validation/dist/jquery.validate.js', ['depends' => 'app\assets\AppAsset']);
        $this->view->registerJsFile('js/cart_show.js', ['depends' => 'app\assets\AppAsset']);
        return $this->render('show', ['cart'=>$cart, 'modelForm' => $modelForm]);
    }






    public function actionAdd()
    {
        $cart = $this->getCart();
        /* post param */
        $product_id = Yii::$app->request->post('product_id') ?: null;
        $quantity = (int)Yii::$app->request->post('quantity') ?: null;
        $get_html = Yii::$app->request->post('get_html');

        /* check AJAX */
        if (false == Yii::$app->request->isAjax) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
            /* check $post */
        } elseif ( false == Yii::$app->request->isPost || !$product_id || !$quantity ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
            /* check $product_id, get $product */
        } elseif ( !$product = Product::findOne(Yii::$app->request->post('product_id')) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }

        Yii::$app->response->format = Response::FORMAT_JSON;

        $cart->put($product, $quantity);
        $html_block = ( empty($get_html) ) ? null : LeftCartWidget_oneItem::widget(['product'=>$product]);

        $response = [
            'count'      => Product::getQuantityWord($this->cart),
            'html_block' => $html_block,
            'cost'       => sprintf( "%.2f", $cart->getCost()),
        ];

        return $response;
    }




    public function actionDeduct()
    {
        $cart = $this->getCart();
        /* post param */
        $product_id = Yii::$app->request->post('product_id') ?: null;
        /* check AJAX */
        if (false == Yii::$app->request->isAjax) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
            /* check $post */
        } elseif ( false == Yii::$app->request->isPost || !$product_id ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
            /* check $position */
        } elseif ( !$position = $cart->getPositionById(Yii::$app->request->post('product_id')) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }
        Yii::$app->response->format = Response::FORMAT_JSON;

        $position->quantity -= 1;
        if ($position->quantity < 1) { $cart->remove($position); }
        $cart->saveToSession();

        $response = [
            'prod_count' => $position->quantity,
            'totalCount' => Product::getQuantityWord($cart),
            'cost' => sprintf( "%.2f", $cart->getCost()),

        ];
        return $response;
    }



    public function actionUpdate()
    {
        $cart = $this->getCart();
        $modelForm = new ChangeCartPositionForm();
        /* check AJAX */
        if ( false == Yii::$app->request->isAjax ) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
        }
        elseif ( !$modelForm->load(Yii::$app->request->post()) ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
        }
        elseif ( !$modelForm->validate() ) {
            throw new NotFoundHttpException($this->errorMsg['notValid']);
        }
        elseif ( !$position = $cart->getPositionById($modelForm->product_id) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }
        Yii::$app->response->format = Response::FORMAT_JSON;

        $position->setQuantity($modelForm->quantity);
        $cart->saveToSession();

        $response = [
            'prod_cost' => sprintf( "%.2f", $position->cost),
            'cost' => sprintf( "%.2f", $cart->cost),
            'totalCount' => Product::getQuantityWord($cart),
        ];
        return $response;
    }



    public function actionDelete()
    {
        $cart = $this->getCart();
        $modelForm = new ChangeCartPositionForm();
        /* check AJAX */
        if ( false == Yii::$app->request->isAjax ) {
            throw new NotFoundHttpException($this->errorMsg['notAjax']);
        }
        elseif ( !$modelForm->load(Yii::$app->request->post()) ) {
            throw new NotFoundHttpException($this->errorMsg['notPostParam']);
        }
        elseif ( !$modelForm->validate() ) {
            throw new NotFoundHttpException($this->errorMsg['notValid']);
        }
        elseif ( !$position = $cart->getPositionById($modelForm->product_id) ) {
            throw new NotFoundHttpException($this->errorMsg['badId']);
        }
        Yii::$app->response->format = Response::FORMAT_JSON;

        $cart->remove($position);
        //$cart->saveToSession();

        $response = [
            'cost' => sprintf( "%.2f", $cart->cost),
            'totalCount' => Product::getQuantityWord($cart),
        ];
        return $response;
    }



    /**
     * Fill top menu
     *
     * @param array $category_roots
     * @param string $top_button
     * @return array
     */
    protected function setTopMenuButtons(array $category_roots, $top_button = null)
    {
        $top_button =  $top_button ?: 'index';
        $activeButtons = [ 'index' => '', 'about' => '', 'contact' => ''];
        /* add Category button in menu */
        if ( !empty($category_roots) ) {
            foreach ($category_roots as $root) {
                $activeButtons[$root->name] = '';
            }
        }
        /* set class 'active' for button */
        if ( array_key_exists($top_button, $activeButtons) ) {
            $activeButtons[$top_button] = 'active';
        }
        return $activeButtons;
    }


}

controllers/OrderController.php
<?php
/**
 * Created by PhpStorm.
 * User: Toha
 * Date: 07.04.2018
 * Time: 18:49
 */

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use Yii;
use yii\web\Controller;
use app\models\Customer;
use app\models\Order;
use yz\shoppingcart\ShoppingCart;
use app\models\forms\CustomerForm;
use app\components\DataLayoutTrait;
use app\components\exceptions\CustomException;

class OrderController extends Controller
{
    use DataLayoutTrait;


    public function beforeAction($action)
    {
        $top_button = $action->id;
        /* get all roots */
        $this->category_roots = Category::find()->roots()->all();
        /* set category_roots in main for draw topMenu */
        $this->view->params['category_roots'] = $this->category_roots;
        /* set quantity products */
        $this->view->params['cart_quantity'] = Product::getQuantityWord($this->getCart());
        $this->view->params['active_buttons'] = $this->setTopMenuButtons( $this->category_roots, $top_button );

        return parent::beforeAction($action);
    }

    /**
     * Show customer form
     *
     * @return string
     */
    public function actionCustomerForm()
    {
        $formModel = new CustomerForm();
        $user = Yii::$app->user->identity;

        $cart = new ShoppingCart();
        try {
            if ($cart->isEmpty) {
                $except = new CustomException( 'Пустая корзина || actionCustomerForm()');
                throw $except->infoExcept('Чтобы оформить заказ необходимо выбрать товар.');
            }
        } catch (CustomException $e) {
            $e->init();
        }

        return $this->render('customer_form', compact('formModel', 'user'));
    }


    /**
     * Create order
     *
     * @return string
     * @throws \yii\db\Exception
     */
    public function actionCreateOrder()
    {
        $cart = new ShoppingCart();
        $user = Yii::$app->user->identity;
        $formModel = new CustomerForm();

        $transaction = Yii::$app->db->beginTransaction();

        //dd($customer_id);
        /* тут оказия если пользователя нет */
        if (!$user) {
            return Yii::$app->runAction('site/index');
        }
        /* и тут оказия если customer нет */
        if ( !isset($user->customer->id)) {
            return Yii::$app->runAction('site/index');
        }


        try {
            if ( $formModel->load(Yii::$app->request->post()) && $customer = $formModel->fillModel( $user->customer->id)) {
                /* set order */


                dd($customer);
                $order = Order::setOrder($customer, $cart);
                /* set order-items */
                Order::setOrderItems($order, $cart);
                /* set last_order_id */
                $customer->setLastOrderId($order->id);
                if (!empty($user)) {
                    $user->saveCustomerId($customer->id);
                }
                $this->sendOrderEmail($customer, $order);
                Yii::$app->session->setFlash('success', 'Спасибо за заказ.', false);
                $cart->removeAll();
                $this->redirect(Yii::$app->getHomeUrl());
            }

            $transaction->commit();

        } catch (CustomException $e) {
            $transaction->rollBack();
            $e->init();
        }
        return $this->render('customer_form', compact('formModel', 'user'));
    }


    /**
     * @param Customer $customer
     * @param Order $order
     * @throws CustomException
     */
    public function sendOrderEmail(Customer $customer, Order $order) {
        try {
            Yii::$app->mailer->compose()
                ->setFrom('al-loco@mail.ru')
                ->setTo((string)$customer->email)
                ->setSubject('Заказ №' . $order->id)
                ->setTextBody($customer->first_name . ', ваш заказ № '. $order->id . ', спасибо за доверие.')
                ->send();
        } catch (\Throwable $e) {
            $except = new CustomException( $e->getMessage() . '|| sendOrderEmails()');
            throw $except->errorExcept('Не удаётся оформить заказ, такого email нет.');
        }
    }




    /**
     * Fill top menu
     *
     * @param array $category_roots
     * @param string $top_button
     * @return array
     */
    protected function setTopMenuButtons(array $category_roots, $top_button = null)
    {
        $top_button =  $top_button ?: 'index';
        $activeButtons = [ 'index' => '', 'about' => '', 'contact' => ''];
        /* add Category button in menu */
        if ( !empty($category_roots) ) {
            foreach ($category_roots as $root) {
                $activeButtons[$root->name] = '';
            }
        }
        /* set class 'active' for button */
        if ( array_key_exists($top_button, $activeButtons) ) {
            $activeButtons[$top_button] = 'active';
        }
        return $activeButtons;
    }



    /******** TEST **********/
    /***********************/

    public function actionTest()
    {

        $test = [
            'key' => 'value',
        ];
        return $this->render('test', compact('test'));

    }



}

views/cart/show.php
<?php

/* @var $cart ShoppingCart */

use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yz\shoppingcart\ShoppingCart;



$positions = $cart->positions;

?>
<style>
    .wrap_message {
        min-height: 40px;
        min-width: 280px;
        padding: 14px 0 0 10px;
    }

    .wrap_message .message {
        display: none;
    }

    .wrap_message .message .invalid {
        color: #a94442;
    }
</style>
<!-- begin:article -->
<div class="row" id="cart_show">

    <!-- begin:content -->
    <div class="col-md-12 col-sm-12 content">

        <div class="row" id="cart_nav">
            <div class="col-md-7">
                <h3>Корзина</h3>
            </div>
<!--            <div class="col-md-5">-->
<!--                <ul class="nav nav-pills pull-right">-->
<!--                    <li class="active"><a href="#">Корзина</a></li>-->
<!--                    <li><a href="#">Данные покупателя</a></li>-->
<!--                </ul>-->
<!--            </div>-->
        </div>

        <div class="row">
            <div class="col-md-12">

                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Фото</th>
                        <th>Описание</th>
                        <th>Количество</th>
                        <th>Цена</th>
                        <th>Сумма</th>
                    </tr>
                    </thead>
                    <tbody id="container_cart_show">

                    <? foreach ($positions as $position) { ?>
                        <tr data-product_id='<?= $position->id ?>'>
                            <td><img src="<?= Url::to('@prodImg/'.$position->img); ?>" class="img-cart" /></td>
                            <td><strong><?= $position->description; ?></strong><!--<p>Размер</p>--></td>
                            <td>
                                <!-- Form
                                ------------->
                                <? $form = ActiveForm::begin(['options' => ['class'=>'form-inline'], 'validateOnSubmit' => false]); ?>
<!--                                <form action="/cart/show" class="form-inline">-->
                                    <div class="form-group">
                                        <input class="form-control" type="text" value="<?= $position->quantity; ?>" name="ChangeCartPositionForm[quantity]" autocomplete="off" />

                                        <input type="hidden" value="<?= $position->id; ?>" name="ChangeCartPositionForm[product_id]" />

                                        <button rel="tooltip" title="Сохранить" class="btn btn-default" name="action" value="update">
                                            <i class="fa fa-pencil"></i>
                                        </button>
                                        <button rel="tooltip" title="Удалить" class="btn btn-primary" name="action" value="delete">
                                            <i class="fa fa-trash-o"></i>
                                        </button>
                                        <!--                                    <a href="#" class="btn btn-primary" rel="tooltip" title="Delete"><i class="fa fa-trash-o"></i></a>-->

                                        <div class="wrap_message">
                                            <div class="message">

                                            </div>
                                        </div>
                                    </div>
<!--                                </form>-->


                                <? ActiveForm::end() ?>
                            </td>
                            <td><span class="product_price"><?= sprintf( "%.2f",($position->price) ) ?></span> p</td>
                            <td><span class="product_cost"><?= sprintf( "%.2f",($position->cost) ) ?></span> p</td>
                        </tr>
                    <? } ?>



                        <tr>
                            <td colspan="6">&nbsp;</td>
                        </tr>
    <!--                    <tr>-->
    <!--                        <td colspan="4" class="text-right">Total Product</td>-->
    <!--                        <td>$86.00</td>-->
    <!--                    </tr>-->
    <!--                    <tr>-->
    <!--                        <td colspan="4" class="text-right">Доставка</td>-->
    <!--                        <td>$2.00</td>-->
    <!--                    </tr>-->
                        <tr>
                            <td colspan="4" class="text-right"><strong>Общее кол-во</strong></td>
                            <td id="inTableTotalCount"><?= $cart->count; ?></td>
                        </tr>
                        <tr>
                            <td colspan="4" class="text-right"><strong>Общая сумма</strong></td>
                            <td><span class="cart-cost"><?= sprintf( "%.2f",($cart->cost) ) ?></span> p</td>
                        </tr>
                    </tbody>
                </table>

                <a href="categories.html" class="btn btn-default">Продолжить покупки</a>
                <a href="<?= Url::to('/order/customer-form') ?>" class="btn btn-primary pull-right <? if ($cart->isEmpty) { echo 'disabled'; } ?>"  >Далее</a>
            </div>
        </div>
    </div>
    <!-- end:content -->
</div>
<!-- end:article -->